name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
  - type: textarea
    id: environment
    attributes:
      label: Describe your environment
      description: |
        Please describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.
      value: |
        OS: (e.g., Ubuntu 20.04)
        Python verison: (e.g., Python 3.8.10)
        SDK Version: (e.g., )
        API Version: (e.g., )
  - type: textarea
    attributes:
      label: What happened?
      description: Please provide as much detail as you reasonably can. Describe exactly how to reproduce the error. Include a code sample if applicable.
      value: |
        ## Description

        ## Steps to reproduce

        ## Expected behavior

        ## Actual behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
      placeholder: "Any additional information..."
  - type: dropdown
    id: contribute
    attributes:
      label: Would you like to implement a fix?
      description: |
        If you plan to implement a fix for this, check this box to let the maintainers and community know (you can update this later if you change your mind).
        Refer to the [contribution guide]() for tips on getting started.
      options:
        - "No"
        - "Yes"
    validations:
      required: false
