contact_links:
  - name: GitHub Discussions
    url: https://github.com/open-telemetry/opentelemetry-python/discussions/new/choose
    about: Please ask questions here.
  - name: Slack
    url: https://cloud-native.slack.com/archives/C03GDP0H023
    about: Or the `#otel-python` channel in the CNCF Slack instance.